### ISSUE TITLE
Build command

### ISSUE THREAD

**Issue by hupili** [initiumlab/initiumlab.com#116]
@andyshuxin  how about changing:

* `grunt build:complete` --> `grunt build`
* `grunt build` --> `grunt build:quick`

Our usual flow for other projects are `grunt build` + `grunt deploy:{target}`. The new notation is easier to remember.

**Comment by andyshuxin** [comment]
@hupili Agree.

**Comment by andyshuxin** [comment]
Fixed with https://github.com/initiumlab/initiumlab.com/commit/26f07360006926496dbe5680831df26c8f3b727f

Now, the default behaviour of `grunt build` is perform a complete build. `grunt build:quick` makes a quick build. `grunt build:complete` is now just an alias to `grunt build`, which also makes a complete build.
