### ISSUE TITLE
On firefox browser, youtube video is down

### ISSUE THREAD

**Issue by yyfjmb** [initiumlab/initiumlab.com#33]
It appears on Firefox 40.0.3, OSX 10.10.5. Instead of loading youtube video, the browser ask you to download a file.

![image](https://cloud.githubusercontent.com/assets/7417451/9901275/18434050-5c99-11e5-93b7-2aacd4b53e19.png)

**Comment by andyshuxin** [comment]
@yyfjmb How about now?

**Comment by yyfjmb** [comment]
fixed @andyshuxin

**Comment by hupili** [comment]
@yyfjmb as a convention, please leave pointers before closing issue. A sentence describing how the problem is fixed should be enough. If the fix is done with in the Git/GitHub eco-system, you can simply leave the commit number or link. 

## Example 1

```
Fixed in https://github.com/initiumlab/initiumlab.com/commit/0ad79543ebc56010220b874f5b355a5d58e65cfe
```

Fixed in https://github.com/initiumlab/initiumlab.com/commit/0ad79543ebc56010220b874f5b355a5d58e65cfe

## Example 2

```
Fixed in
0ad79543ebc56010220b874f5b355a5d58e65cfe
```

Fixed in
0ad79543ebc56010220b874f5b355a5d58e65cfe

**Comment by hupili** [comment]
GitHub has good rendering of those notations. People can also jump to the relevant commit directly to check or learn how the problem gets fixed.
