### ISSUE TITLE
Social sharing functionality

### ISSUE THREAD

**Issue by hupili** [initiumlab/initiumlab.com#91]
* FB, Twitter, Weibo...
* WeChat (QR Code)

**Comment by andyshuxin** [comment]
Added by https://github.com/initiumlab/hexo-theme-next/commit/81bbbbe4393796c9c1ec5e34068883809ed46d9e and https://github.com/initiumlab/hexo-theme-next/commit/b4ec2372af26d339961f8ed3e17646175e64a409 .

@frankinit Need testing on this. Some of them won't work on localhost or staging server due to URL issues.

**Comment by frankinit** [comment]
@Kateliuxue Would you please test this? Thanks.

**Comment by andyshuxin** [comment]
@frankinit @Kateliuxue 
Most social sharing only work on the main site due to URL issues. Can we perform a regression test on the staging version and deploy to production server, so that they can be tested?
Thanks.

**Comment by Kateliuxue** [comment]
@andyshuxin 
Sharing function works well, but there are some bugs when sharing.
Both on window 8.1 Chrome & Mac ios.

![default](https://cloud.githubusercontent.com/assets/14042060/10244118/c5db08ea-692f-11e5-8a4a-106c190b4cb4.jpg)

Words go out of the box line.
![default](https://cloud.githubusercontent.com/assets/14042060/10244122/d0824e8e-692f-11e5-9701-e912754ac6d2.jpg)

wordings without spacing:
![default](https://cloud.githubusercontent.com/assets/14042060/10244125/d6b57b78-692f-11e5-97ae-20c373c2bb24.jpg)

**Comment by andyshuxin** [comment]
These problem are embeded in JiaThing, the social plugin service we use, and are difficult to handle without hacking their JavaScript code.

We shall build our own social sharing components to solve these problems once and for all.
Related issue:https://github.com/initiumlab/initiumlab.com/issues/112

This issue is closed and future discussion could move to #112 .
